// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTMdFVwqUr7Y_lMxu0HeyhRbdNfnNKrKg',
    appId: '1:939108678228:web:ba469e6c3dae6bde554bc1',
    messagingSenderId: '939108678228',
    projectId: 'pimo-project-66700',
    authDomain: 'pimo-project-66700.firebaseapp.com',
    storageBucket: 'pimo-project-66700.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtqz9zkR_Wym-crB-rAxaYnRWgsbRVUG4',
    appId: '1:939108678228:ios:f30f2cab1c5b55df554bc1',
    messagingSenderId: '939108678228',
    projectId: 'pimo-project-66700',
    storageBucket: 'pimo-project-66700.firebasestorage.app',
    iosClientId: '939108678228-n8ou8bt5cfspbkn2shaab135greb0085.apps.googleusercontent.com',
    iosBundleId: 'com.example.agnoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTMdFVwqUr7Y_lMxu0HeyhRbdNfnNKrKg',
    appId: '1:939108678228:web:532307ba46218d97554bc1',
    messagingSenderId: '939108678228',
    projectId: 'pimo-project-66700',
    authDomain: 'pimo-project-66700.firebaseapp.com',
    storageBucket: 'pimo-project-66700.firebasestorage.app',
  );

}